trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: JeringTech/DevOps.AzurePipelines
    ref: refs/tags/0.2.0
    endpoint: JeringTech

jobs:
- template: templates/nuget/main.yml@templates
  parameters:
    changelogPath: "Changelog.md"
- template: templates/docs/main.yml@templates