trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: JeringTech/DevOps.AzurePipelines
    endpoint: JeringTech

jobs:
- template: templates/nuget/main.yml@templates
  parameters:
    outOfProcessBuildDependencies: ["nodejs"]
    codecovKey: "e5de9f48-fb06-43c6-8368-44de5cf7e5d4"
    cacheYarnPackages: true
